import { Providers } from "@/providers/Providers";

import type { Metadata } from "next";
import { Noto_Serif, Be_Vietnam_Pro, DM_Mono } from "next/font/google";
import "./globals.css";

const NotoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});

const BeVietnamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

const DMMono = DM_Mono({
  variable: "--font-dm-mono",
  weight: ["300", "400", "500"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${NotoSerif.variable} ${BeVietnamPro.variable} ${DMMono.variable} h-full antialiased`}
    >
        <body className="min-h-full flex flex-col">
          <Providers>
            {children}
          </Providers>  
        </body>
    </html>
  );
}
